server:
  port: 8099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      auto-commit: false
    url: jdbc:mysql://localhost:3306/house
    username: root
    password: zsxdc153
  servlet:
    sesssion:
      timeout: 1800
    multipart:
      max-file-size: 10MB # 文件上传 - 最大上传大小
      max-request-size: 100MB # 文件上传 - 最大访问大小
  redis:
    host: localhost
    port: 6379
#    password: zsxdc153
  session:
    store-type: redis
    timeout: 60s  # 1分钟过期

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resource:
#    add-mappings: false

# 文件上传
file:
  upload:
    base-dir: uploads/
    access-path: /files/**